// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ioqatuafacqchpgtijne.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvcWF0dWFmYWNxY2hwZ3Rpam5lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNDQ2MzksImV4cCI6MjA2MjgyMDYzOX0.PliIq8OSpv9gnucwcyRvadkN_QqKSfyzIeTO1nMZ5-Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);